name: Application CI
on: [push, pull_request]
jobs:
    pipeline:
        name: pessoa pipeline
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.pull_request.title, '[skip ci]') && !contains(github.event.pull_request.title, '[ci skip]')"
        timeout-minutes: 40
        env:
            NODE_VERSION: 16.17.0
            SPRING_OUTPUT_ANSI_ENABLED: DETECT
            SPRING_JPA_SHOW_SQL: false
            JHI_DISABLE_WEBPACK_LOGS: true
            NG_CLI_ANALYTICS: false
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 16.17.0
            - uses: actions/setup-java@v1
              with:
                  java-version: '17.x'
            - name: Install node.js packages
              run: npm install
            - name: Run backend test
              run: |
                  chmod +x mvnw
                  npm run ci:backend:test
            - name: Package application and deploy image
              env:
                REGISTRY_USER: ${{secrets.REGISTRY_USER}}
                REGISTRY_PASSWORD: ${{secrets.REGISTRY_PASSWORD}}
              run: npm run java:docker:deploy:image
            - name: Deploy to Heroku
              if: github.event_name == 'push' && github.ref == 'refs/heads/main'
              env:
                  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
              run: |
                  if [ ! -z "$HEROKU_API_KEY" ]; then
                      ./mvnw -ntp com.heroku.sdk:heroku-maven-plugin:2.0.5:deploy -DskipTests -Pprod -Dheroku.buildpacks=heroku/jvm -Dheroku.appName=agile-badlands-61531
                  else
                      echo No HEROKU_API_KEY, skipping...
                  fi
